### ISSUE TITLE
How do you come up with those super-awesome side-project ideas?

### ISSUE THREAD

**Issue by abhisheksoni27** [notwaldorf/ama#101]
I am asking because that's something I sometimes struggle with, sort of like a writer's block and I wonder how you come up with those ideas. Be it emoji-translate, or Tenori-off, those projects are super cool and it is intriguing as to where you find inspiration for them.

Also, do you have a fixed schedule or a window in your day in which you work on side-projects?

**Comment by notwaldorf** [comment]
Oh noooo sorry I didn't reply to this. But the good news is, I think I have a better answer now than I did in August! lol

I can very strongly relate to writer's block because i tend to go through a big idea drought. My "good" projects are really spaced between, because i'm at the mercy of when something good comes up. `emoji-translate` started out of meeting @muan and hearing about her [emoji-lib](https://github.com/muan/emojilib), and me wanting to do something with it. I made `tenori-off` because i wanted to play with [magenta.js](https://github.com/tensorflow/magenta-js) and didn't really know what to build. Actually, maybe that's how i build a lot of my projects -- there's something I want to use, and I struggle to make an idea fit it. 

But that's not really sustainable for me, so I tried to tackle this idea of creativity on demand in my inktober this year (I just wrote [a blog post](https://meowni.ca/posts/inktober/) about it), and i think it worked a little bit!! I now have way more ideas than I did before (actually, for the first time in my life, I have more ideas that time to implement them).

The thing that worked for me is having a very solid constraint about what the project is about (in the inktober case, "a blob of emoji"), and then seeing something in the real world and forcing myself to apply it to that project. Can I use this print visual for that blob? Can I use sounds? Can I use a marquee element anywhere in it? If I used a microphone, how would this affect the visual? And whilst at the beginning I would say "no, that sounds dumb" to a lot of ideas, I added them to a list anyway and by the end of the month (after grinding on this level for like 30 days), things seemed way more doable.
