### ISSUE TITLE
Some random questions 

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#108]
Hello,

Here are some random questions:

1) Which type of switch do you prefer in mechanical keyboards? 
2) Will you ever try/use a Ducky keyboard?
3) I do not like typescript. I feel that types(to that extreme) should be used on compiler languages and not interpreted languages.  What is your take on typescript and do you use it?

Thanks,
-Darin

**Comment by notwaldorf** [comment]
Here are some random answers:
1. I am not a fan of clickiness, so I have pretty quiet switches. My 60% has cherry browns, my MiniVan has purple kailh pros. My ortho niu-40 has cherry browns as well, but I don't use this keyboard very much (because of the ortho part not the switches part).
2. I don't know what a Ducky keyboard is! I don't really have an allegiance to brands of keyboards. My 60% is a gk-64 because it's the best keyboard (for me) that I have found. The Minivan I picked because I wanted a staggered 40%, and this was the best option I could find.
3. I had some pretty negative feelings about TypeScript when I started using it, but after a while I came to this conclusion:
    - I think TypeScript is great if you're developing a library. Having the confidence that the types you expect in a function are the types you're using is pretty great, and it has absolutely caught bugs for me that I wouldn't have seen for a while. A lot of the code I'm writing nowadays isn't very testable, so I'll take anything that makes me slightly more confident that a user won't file a bug that a function I wrote doesn't work. I mean, it probably won't work for other reasons, but it's not because I miswrote the API, at least
   - I think TypeScript sucks for writing small apps, and all the demos I build are in JavaScript. Sometimes you have to write some hacks, and TypeScript is not really keen on hacks, and I'm not really keen on fighting with it.
