### ISSUE TITLE
What is your main sources of procrastination, and how do you feel about them?

### ISSUE THREAD

**Issue by duch11** [notwaldorf/ama#110]
What's your favorite, why?
What's your least favorite, why?
Maybe also why would you find yourself procrastinating?

**Comment by notwaldorf** [comment]
Finally getting to this -- ironically, this repo causes me to procrastinate!

In my coding life, I generally procrastinate when I have a tedious task ("do a refactor"), or something that is a bit hairy and I haven't figured out how to split it into small tasks that don't cause me anxiety. I tend to procrastinate very little at work, actually, because work is a very focused task for me. I know what I have to do, and I do it. I tend to procrastinate by doing more work, so this usually works out!

I procrastinate a ton in my real life, usually around tedious tasks again (going to the DMV, calling to cancel a subscription, mailing taxes), or tasks that have a high chance of me overthinking them (like replying to emails or amas), which stresses me out, and I tend to just...avoid them. In real life I procrastinate by watching a ton of garbage tv or playing video games or reading or walking my dog or just doing normal human stuff. Unclear if any of this is actual procrastination and not just...living life lol.
