### ISSUE TITLE
Knowing a lot about a little vs knowing a little about a lot 

### ISSUE THREAD

**Issue by tiggreen** [notwaldorf/ama#112]
Thanks for all your blog posts and projects! I really enjoy reading your posts :) 

While I was reading your past year review I noticed this thought. 
 
>I understand many things well enough to have opinions and advice, but not well enough to be an expert in any of them. This is the thing I want to figure out this year.

I'm curious did you figure this out and if yes, what helped you to make a decision? 

I'm asking because I'm currently struggling with this.

Thank you! 🙏🏻

**Comment by notwaldorf** [comment]
I did!!! I ended up working on the [PWA Starter Kit](https://github.com/Polymer/pwa-starter-kit) project and I had to come to terms with all of these things. I had to learn about bundling and redux and theming and routing because that was literally my task. 

I've had another year to grow since then, and I've become comfortable with the fact that I am the kind of person that only learns things when she needs them. For example, my breadth of web knowledge is big (i know a little about a lot of things), and for some specific things like web components, performance, pwas, i know _a lot_ . I honestly think this is the only way to do it -- there's not a chance you can be really good at everything (at least not for the vast majority of us), so the next best thing you can do is know a little bit about everything, and go in depth if and when you need to.
