### ISSUE TITLE
Preferred Cell Phone And Synth Band Questions

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#115]
Couple of random questions: 

1) With the new Pixel phone coming out, do you use a Pixel? If not...what is cell phone do you prefer to use? 

2) Since you do music apps.... do you like synth music group called a-ha?

**Comment by notwaldorf** [comment]
1. I'm unfortunately locked into the iOS ecosystem, not because I think it's a better choice, but because i want to use imessage. I am not a "buy the latest phone" kind of person though, so I'm still on my iPhone X (which I did but when it came out, only because I had an iPhone 6 with a battery life of 2 hours)

2. I love "take on me" but i can't say that I've ever listened to more songs than that. I always thought they were a one hit wonder!
