### ISSUE TITLE
Piano-scribe is AMAZING! There's a few issues, though...

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [notwaldorf/ama#124]
Piano-scribe is an indispensable transcription program I want to thank you for creating it (or co-creating it, no idea). I haven't even found commercial software can match its' quality. 

I've noticed two issues though, and I also have a question. There's no way to contact you on the project itself, so I'm asking here:

1. Uploading audio clips longer than 1 minute simply makes the page hang indefinitely, and nothing happens. I've managed to bypass this by splitting my audio into 1 minute segments before uploading. 

2. When the transcription is done and it plays in the browser, it sounds (and looks) excellent. However, the downloaded MIDI files have the note lengths wrong - there's a few enormously long notes, while all other notes are incredibly short. [Here's what that looks like](https://i.imgur.com/RMxOzmt.png), and here's links to the [buggy MIDI](https://mega.nz/file/XjBkSJCb#O7G_9j_I6eOo1Wi7NVYBHiBfb0CuISPLm0ujmIS0CIo) in the image and [the original audio input](https://mega.nz/file/r6YmkZ6Q#EVofdfUCdqmQ0QEl8NdE9ufjuIuBt8b75L0Ni9UFYKA) for comparison. I've managed to bypass the issue by manually correcting the note lengths, but it can get quite tedious.

3. How hard would it be to make this into a standalone program? Online services have a way of disappearing, and it would be an incredible shame to lose this project forever if Glitch gets goes bankrupt/bought out/whatever.

**Comment by notwaldorf** [comment]
Yay, so happy you like it!

> How hard would it be to make this into a standalone program? 

All Glitch projects are git repos, so that would be super straightforward! I'm not very concerned about Glitch disappearing without notice, but I do have a very long standing TODO item to back up all of the Magenta Glitch projects as repos in our org so....one day!

> When the transcription is done and it plays in the browser, it sounds (and looks) excellent. However, the downloaded MIDI files have the note lengths wrong 

Hmm, I wonder if there's a problem with the magenta.js <-> NoteSequence converter. Not sure what's up with that, but I would really appreciate it if you could open it as an issue on the [magenta-js](https://github.com/magenta/magenta-js) repo.

> Uploading audio clips longer than 1 minute simply makes the page hang indefinitely 

Yeahhhhhhhh doing all that processing in the browser is very expensive and takes forever, and I think the browser just gives up on it. You might want to take a look at the Python [onsets and frames](https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription) model, which is what that demo uses. There should be a notebook that you can use, where you might have a better chance with long files!

**Comment by iFUCKINGHATEcomputers** [comment]
Thank you! I've raised the issue, and I'll check out that python model in the meantime.
