### ISSUE TITLE
Work/fun language choice

### ISSUE THREAD

**Issue by eush77** [notwaldorf/ama#19]
You mentioned that you are a C++ developer at work, but your public repositories on GitHub are mostly in JavaScript. Do you have any side projects in C++?

If not or few, is it because the language is not very appealing to you or is it just not suitable for the things you want to be doing in your free time? How does the switching back and forth between these languages influence the way you think and code in them?

What other programming languages are you experimenting with?

**Comment by notwaldorf** [comment]
Ooof, this is a really good question.

I used to be a C++ developer until earlier this year, when I joined the Polymer team. Most of my pet projects were in JS because after 8 hours of having the compiler be solidly disappointed in me, I wanted fun code to be fun (and compared to C++, JS is hiiiiiiilarious to work in). 

Now that I work with JS, I find that my pet projects are still in JS. I don't think I work on very serious things outside of work (they're all either trolling, or about emoji, or both), and I'm kind of sold on this web thing, so it's still unlikely I would pick up C++ for funsies. Sometimes I try to do something in Ruby, just to force myself to be uncomfortable in a language, but it's not super often.

C++ is still my favourite language, but it's not necessarily the one I have the most fun in, and I am a strong believer that whatever you do in your free time, whether it's coding or knitting sweaters for penguins, should be incredibly fun.
