### ISSUE TITLE
Top 3 Emoji utilities

### ISSUE THREAD

**Issue by surma** [notwaldorf/ama#2]
Emoji keyboards⌨, dictionaries📖, websites💻, whatever❓ 

Your top ➂ resources for anything emoji!

**Comment by notwaldorf** [comment]
- [emoji cheat sheet](http://www.emoji-cheat-sheet.com/) so that I can put emoji in my commit messages (though I'm trying to use [mojibar](https://github.com/muan/mojibar) instead)
- I use [twemoji](https://github.com/twitter/twemoji) in a lot of projects, because I think they're prettier than the default Apple emoji, and at least you know they render everywhere
- I recently got the emoji [keyboard](http://emojikeyboard.club/) and it's pretty great. (sidebar: if you have it and are worried about installing their sketchy mysterious app (you should be, lol keyloggers), just dig through the package until you find the `keylayout` file)

:sparkles: bonus funsies :sparkles: 
- if I'm having a bad day, the [emoji-translate](https://chrome.google.com/webstore/detail/emoji-translate/kkkfndlpdajmbgofkidemhkjoinhmojl) extension is kind of silly (but I made it so this is a #brag)
- @muan made a [megamoji](http://megamoji.muan.co) app and it's the best

**Comment by dandv** [comment]
What a [black&white](https://genius.com/Meat-loaf-id-do-anything-for-love-but-i-wont-do-that-lyrics) developer's life due to [colorful emojis not visible in WebStorm on Fedora](https://youtrack.jetbrains.com/issue/IJPL-173762/No-colorful-emojis-on-Fedora) :disappointed:
