### ISSUE TITLE
Where's the best Poutine in Montreal?

### ISSUE THREAD

**Issue by ThirdMoonSoftware** [notwaldorf/ama#22]
There has to be somewhere better than just Montreal Poutine in Old Montreal right? :)

**Comment by notwaldorf** [comment]
Oh god, definitely. La Banquise is the most popular with tourists, because it has a billion choices (but locals don't tend to eat there). I am biased towards the poutine at Frite Alors, because they have Belgian fries and they're onnnnn point. The pulled pork poutine there is my favourite by far.

Poutineville is also delicious, but it was always a bit too far from my house, so I didn't go there often.
