### ISSUE TITLE
Have you seen this?

### ISSUE THREAD

**Issue by tisnman** [notwaldorf/ama#24]
http://emojiparty.club/

![Image of Emoji purr...urr...ty](http://i.imgur.com/k4meKzp.png)

**Comment by notwaldorf** [comment]
I think @addyosmani was technically the first person to show it to me, but don't worry: I play with it every [time](http://emojiparty.club/%F0%9F%A7%80%F0%9F%A6%84%F0%9F%98%B9) somebody sends me the link. 😂

**Comment by notwaldorf** [comment]
Related: oooof. are you using Chrome on Linux? Why are your emoji so sad in the menu?

**Comment by tisnman** [comment]
no, Chrome Version 46.0.2490.80 m on Win10. Those squares are the skin tone modifier I believe D';

Here's it on a virtual machine ubuntu. Many more missing emojis. http://i.imgur.com/AJnY1zL.png http://i.imgur.com/1O8xr6n.png

**Comment by notwaldorf** [comment]
Ah, okay, I understand now. Windows is definitely not ready for the skin tone modifiers (I thought you were just missing random emojis, which was scary), and the Linux Emoji font is super sad. Since Chrome uses the native OS Emoji font as a fallback...this is why we can't have nice things. (FYI, I wrote a chrome extension to make this slightly better for you on Linux, if you want: https://github.com/notwaldorf/twemojify)
