### ISSUE TITLE
How did you end up working on Chrome?

### ISSUE THREAD

**Issue by imdevan** [notwaldorf/ama#27]
Is the process any different than interviewing for an engineering position at Google?

**Comment by notwaldorf** [comment]
Nope, I think the process is the same! I applied to the Montreal office, which at the time had two areas, Chrome and Security. Once I got hired, I picked which team I was more interested in (for me it was Chrome Sign-In), and that was that. 

I think different offices might have different approaches to how they distribute people -- not all teams might have head count at all times, and bigger offices might be less flexible about what teams you can choose from. If you're considering interviewing, this would be a great conversation to have with your recruiter early on. It's good for them to know what you're interested in, so that they can keep an eye out for teams that would work for you.

Hope this helped!

**Comment by imdevan** [comment]
Thanks! 😄
