### ISSUE TITLE
Tell us a bit about the chrome devtools team. How was your experience? I work on Edge devtools. Just want to say hi!

### ISSUE THREAD

**Issue by nojvek** [notwaldorf/ama#29]

**Comment by nojvek** [comment]
This is a pretty cool idea btw. I think I will open up an ama repo as well.

**Comment by notwaldorf** [comment]
Hiya! :wave:
Edge is great! I'm super excited to see how fast it's growing!

Bad news bears: I've never worked on the Chrome dev tools (I've never even sent a patch to the dev tools bits!) I was on the Sign In/Identity team in Chrome, and worked on the new [profile](http://chrome.blogspot.com/2014/08/this-time-its-personal.html) management bits.

It was really fun, and I liked it loads! Starting off was kind of daunting, because Chrome is Really Giant™️, but once you get over that it's kind of an amazing experience. It's awesome how much you learn when the code is good (like really good), and the people who review your code are good (like realllllly good).

**Comment by nojvek** [comment]
Thanks.  I look forward to my first contribution.
