### ISSUE TITLE
Sharing is Caring.

### ISSUE THREAD

**Issue by JohnLonginotto** [notwaldorf/ama#30]
I was told that on the day of his daughter's wedding, you can ask the Don for any request and he has to agree to it.
I think it's safe to assume that the same deal is available for web-developers like yourself when an old version of IE is no longer supported (http://meowni.ca/is-ie10-dead/)...? hehe

I was also told you had a Spotify account, and were pretty into music. Would you make a Spotify playlist we can follow? Maybe like a 2016 playlist, or like a coding playlist or something...? Just not a cat-themed playlist please! 😿

**Comment by notwaldorf** [comment]
Oh my! Who are these people telling lies! I do have a Spotify [account](https://open.spotify.com/user/notwaldorf), but it's been very neglected. You can even see from my [last.fm](http://www.last.fm/user/notwaldorf) that I haven't listened to much recently. I'm working on rectifying that!

Soooooo bad news bears for you: I don't usually make any playlists! I tend to listen to whole albums at once, and shuffling between artists realllllly bothers me. My [favourite](https://open.spotify.com/user/notwaldorf/playlist/0KEsM9gtEmM94VIxACXteh) and most played playlist (and I only have like 4 in total) is just Nas songs in the order of how I like them best :) 

For coding, I tend to listen music that I'm really familiar with (so that I don't have to pay attention to it), or without lyrics (so that I don't have to pay attention to it). LCD Soundsystem/Justice/La Roux/Nas/David Bowie/Dire Straits are my faves for that. If I'm doing a really tedious refactor that I have to pay attention to, I usually switch to jazz -- and I'm pretty ignorant of jazz in general, so it's usually whatever @holman has made me listen to recently :)
