### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shimakazekai** [notwaldorf/ama#36]
Since this is an AMA, I'm just gonna ask this directly, where or how can a guy meet a girl like you?
I ask because super smart, funny and beautiful (and a little nerdy) girl like you isn't easy to find.

**Comment by JohnLonginotto** [comment]
Legally change your name to MxMyDzV, then go to the east coast of Cinnabar Island, in the Kanto region. Speak to the Old Man before you go, then Surf along the coast for a while and you will encounter a rare Pokemon.

As a follow-up question for Monica, how often does this sort of thing happen to you in real life and online?
It's no secret that STEM fields have a difficult history with inclusiveness, however I used to think that harassment was, um, not as common as people made it out to be. Like perhaps 90% of women didn't experience it, and 10% speak very loudly. However, now i'm seeing it right before my eyes, it's difficult to ignore. How often does it happen, is it a big problem (for you personally (if that's okay) but also for other women you have worked with), and most importantly, did you experience it before you decided to work in tech (i.e. you had an option to bail on the whole thing, but obviously didn't). 
Also, wouldn't be fair to ask you all these question, but not ask you how you'd help fix it - that would be interesting too :)

**Comment by shimakazekai** [comment]
Very funny. How is that harassment?

**Comment by JohnLonginotto** [comment]
Oh - so you were 100% serious when you were asking where to find super smart, funny and beautiful girls? I miss understood. I thought you were flirting, but you were actually expecting her to reply with the geographic co-ordinates of areas with a high density of smart, funny, beautiful girls, having pillow fights and talking about complex number theory. My bad.

**Comment by shimakazekai** [comment]
You didn't answer my question.
I really doubt she needs your help "defending" herself mr white knight, you're wasting your time.

**Comment by JohnLonginotto** [comment]
Alright weeaboo, let me break it down white-knight style.
Just because anime teaches you that girls are flattered when random men tell them how beautiful they are, doesn't mean real people do. Just because _you_ would be flattered if someone said those things to you, it doesn't mean other people would feel the same way.
This isn't her throw away account like yours. Most of what she talks about is her work, her job in the industry, etc. She uses her real name, talks about her real job, her real cat, etc. So how would it look if some total stranger came to your work and asked you the same question in front of all your friends and co-workers? It's a little... upsetting no?
The problem isn't really what you wrote - I know where you're coming from and I know you didn't mean to offend - the problem is that you didn't realize what you were doing, which is not uncommon, and you will probably go on not realizing until someone really forces you to take the other perspective.

I have a question for you, although i'm not sure how long this thread will last...
What did you expect Monica to reply with?

**Comment by shimakazekai** [comment]
I really doubt **all** of her friends and coworkers check every post here, you really like to exaggerate aren't you? 
If you haven't noticed, this is an AMA, the last A means anything, I don't know why I need to explain this to a PHD student...
As I said before, you're wasting your time, why don't you wait for her to speak for herself? if she doesn't want to answer, fine, if she deletes this fine, but I didn't ask this to argue with you and nobody asked for your help.

**Comment by arackaf** [comment]
>I used to think that harassment was, um, not as common as people made it out to be. Like perhaps 90% of women didn't experience it, and 10% speak very loudly. However, now i'm seeing it right before my eyes, it's difficult to ignore.

I've gone through a very similar education process, thanks to examples like this.  Do some men really make it to adulthood not realizing that crap like this is neither flattering nor endearing?

**Comment by negroslim** [comment]
Harassment is a bit strong, inappropriate seems more apt.

**Comment by OhHiGuizes** [comment]
> I've gone through a very similar education process, thanks to examples like this. Do some men really make it to adulthood not realizing that crap like this is neither flattering nor endearing? 

Unfortunately, yes. I've had friends like that. Some people just never seem to grow up.
