### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by amitmerchant1990** [notwaldorf/ama#42]
Just want to know how do you solve a complicated merge conflict?

**Comment by notwaldorf** [comment]
Patience, patience, patience.

I'm a bit lucky right now because I work on a project where the code is distributed across very many repos, so the merge conflicts within one repo are fairly rare, and easy to fix. When I worked in Chrome, however, it would happen that I would work on a very popular file, that would change daily -- those merge conflicts were pretty brutal.

To be fair, I don't have any good advice. I don't know if there's any tools that help with it -- I just go through every conflict by hand, and reason about which bit should I leave in (my code, the master code, or a bit of both). Having small-ish commits tends to help, since they're easier to reason about.
