### ISSUE TITLE
What's the secret of your amazing technical presentation skill?

### ISSUE THREAD

**Issue by Williammer** [notwaldorf/ama#48]
Hi Monica,

I was redirected from your recent presentation on [Google I/O 2016](https://www.youtube.com/watch?v=zfQoleQEa4w), which is really enjoyable to watch! You've totally nailed it with no effort! : )
As a developer, I've had some difficulties to present technical talks in my company. I tend to get nervous when presenting and this gets worse if there were quite many audiences and some of them were quite picky on what and how I presented my topics.
Watching your talk on Google I/O, I can't even find a little bit nerve from you and it's so fluent and coherent. I wonder what's your secret to present technical talks so well and effortless in front of many people?(especially being gazed by many critical eyes) 
As engineer/developer/emojineer, we normally spend a lot of time in front of computer screen, so we might not have equal amount of time to talk to others compared to other professionals like sales or teacher. Are you just born to be quite good at talking/presenting or were there some kind of hardworking experience/practices that you may share?

Thanks a lot and Best Regards!
William

**Comment by notwaldorf** [comment]
Eeee, thanks so much for the kind words! Really appreciated! ❤️

If it makes you feel any better: I get suuuuper nervous right before a talk, and this is true of most people that I know. It's all about managing that anxiety and converting it into excitement. And whenever I re-watch my talks I find a gazillion flaws with them (i say "like" too much! what are my legs even doing? some sentences make no sense!), which I also think is normal -- hearing yourself speak is one of the most awkward experiences on earth, but it's also the best way to find out what your verbal ticks and stuff are.

I'm a bit lucky because I've done a bit of public speaking and debating in high school (mostly as an excuse to go on trips), so it translates pretty well to giving conference talks. But! It's all about practice, and you can totally get better at it! I find the the best talks are talks that tell stories that you're passionate about -- if you don't really enjoy the subject matter, you're probably not going to be super excited to talk about it either. 

Here's some things that have helped me out a lot:
- Matt Howie has great advice about how to deal with pre-talk nerves: https://medium.com/@mathowie/an-introverts-guide-to-better-presentations-be7e772b2cb5#.dnnf3tmfj
- Zach Holman has a whole website dedicated to preparing and giving talks: http://speaking.io/
- If you find you're not a spontaneous talker, rehearsing your talk over and over is totally okay, and will make you feel super confident as you're giving the talk, since you don't have to make shit up on the spot
- I also watch talks of people that I respect a lot and try to figure out what they do that I enjoy in their talks (and you'd be surprised how many times the spontaneous funnies you hear in a talk are actually prepared and rehearsed!)
- Giving talks (or even lightning talks!) at smaller meetups is a great way to ramp up to bigger conference talks. You can talk about anything! 
- We did this public speaking training recently, and my favourite exercise was this super random thing where you got assigned a random topic and you had to speak passionately for it for like 30 seconds, and then passionately against it for 30 seconds, and maybe flip between them. I got "beets" and turns out 30 seconds of coherent sentences on beets is hella hard, and switching from "beets are the best beets 4 lyf" to "beets: not even once" was kinda difficult! 

Hope this helps, and I hope to see you give a talk soon! 🎉 🍰 🍻

**Comment by Williammer** [comment]
Thank you very much for the tips, very helpful! 
The 30 secs training is particularly awesome, I'm gonna try it too 😃
