### ISSUE TITLE
If no one is using? 

### ISSUE THREAD

**Issue by andrewillard** [notwaldorf/ama#52]
Hi Monica,
First of all, congrats for your talk at Google I/O this year, was my favorite! :+1:

I'm from Brazil :soccer: and I work with Polymer, unfortunately Polymer isn't famous here yet :crying_cat_face:, people are studying frameworks like Angular and React. I can say about Angular, there are more contents and communities that help people know and learn! I'm worried :scream_cat: about people aren't using Polymer, 'cause will be difficult to find professionals, or maybe Google cancel the project :trollface:.

My two questions are:
:one: What do you think about this globally:question:

:two: Why you and others (like @addyosmani) don't help @robdodson with Polycasts:question: It'll amazing release one or two videos per week! :stuck_out_tongue_winking_eye:

Thanks

**Comment by notwaldorf** [comment]
Thanks so much! Google I/O is a big audience, so that's a really nice thing to hear! 🎉🙏

This is just my opinion, obviously, but I don't think Google will be cancelling Polymer any time soon -- there's a lot of fairly big and public [projects](https://github.com/Polymer/polymer/wiki/Who's-using-Polymer%3F) using it, both internally and externally: Google Play Music, YouTube Gaming, the chrome://settings redesign, the new EA Battlefield page, Salesforce, to name a few. I don't know why Polymer isn't super popular in Brazil yet 😿 -- I was recently pleasantly surprised to hear it's growing in Spain (which I didn't expect), so maybe it's just a marketing thing. Hopefully once the Polymer Summit is over we can spend a bit more time reaching out to other communities and fix this! 

I haven't in the past helped Rob with Polycasts because that's not really part of my job 🙃. I'm a core contributor to Polymer, and any of the talks I give tend to be on the side, because I enjoy going to conferences. @robdodson and I have talked about me contributing to some Polycasts soon, but that will be only a couple of episodes -- I still have a bunch of work to do on elements 💪

As for @addyosmani, he's already pretty busy with Totally Tooling Tips and all the million other projects he's involved with -- I'm already concerned he works all the time, I wouldn't want to add extra things to his plate! ❤️

**Comment by robdodson** [comment]
> the new EA Battlefield page

All of [ea.com](http://www.ea.com/) is using them now :D

I think the popularity of Web Components will increase in combination with the number of browsers who have shipped support. When you don't have to use any polyfills anymore I think they will become an extremely attractive option for developers.
