### ISSUE TITLE
When would V1 specs be ready in Polymer?

### ISSUE THREAD

**Issue by retrocausal** [notwaldorf/ama#55]
I am a part of the Polymer slack channel, and things look to be in perspective, and transition to webcomponents V1 already seem to be happening

As an insider, Is there a reasonable ballpark as to when would Polymer completely embrace V1?

Also, a second question.

Would you believe, that speeding up the move to V1, would compromise on Polymer philosophy of working with the platform rather than working around it? That would(Rather would that) make Polymer more abstraction oriented rather than platform oriented

**Comment by notwaldorf** [comment]
Good question! Polymer 2.0 will have the V1 specs ready, and it's already in a preview mode! ([blog post](https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0), [2.0 branch](https://github.com/Polymer/polymer/tree/2.0-preview)). We don't have an exact date as to when we're releasing it, but it should be not long after the Polymer Summit.

I think using V1 is exactly working with the platform (which has been our goal all along). Now that Safari has shipped Shadow DOM, and Edge is working towards it, there's less and less things we need to polyfill (and in particular, less bugs we have to fix because of polyfill and shim limitations). I'm not sure what you mean by "more abstraction oriented rather than platform oriented" -- both Polymer 1.0 and 2.0 have always used the platform, in my opinion :)

**Comment by retrocausal** [comment]
Thanks for taking time out to reply!

What I meant by abstraction oriented than platform oriented, was that I am kinda petrified
That speeding up Polymer 2.0, may mean that the library might stop being a library, and become a framework instead.

Thats just me **paranoid** about the pace at which 2.0 is speeding up to.things might go a miss here and there, or there might be too many changes a developer may need to make etc etc.. 
Guess I can only wait to see what changed!

Oh and Also, who coined "meownica" for you? and why?. I am sorry I just watched your video from google I/O, so asking.

I even shared the I/O link as meow meow, blueberry muffins and webcomponents
![screenshot from 2016-10-07 01-02-05](https://cloud.githubusercontent.com/assets/15086525/19167591/0035bf3a-8c2a-11e6-9b5e-c412aa548d7a.png)

**Comment by notwaldorf** [comment]
Heh, I can't remember if an old non-tech friend called me "Meownica Dinosaurescu" or just coined the "Dinosaurescu" bit; in any case, I found meowni.ca as a domain, so I ran with it. It's probably because i like cats!

I don't think you should worry about Polymer becoming frameworky -- our goal is to become lighter, not heavier. As for the 1.0 -> 2.0 transition, we're doing everything possible to make it incredibly smooth. For example, the Polymer Elements will be in this "hybrid" state where they can be both in 1.0 and 2.0 at the same time, so that you don't have to update your application all at once, and just work on one bit at a time.

**Comment by retrocausal** [comment]
Hey Monica! 

Awesome summit. All supercharged now. 

Ugh, but I hate that imports went away. 

As somebody who knows **absolutely** nothing about modules and module imports, 

what do I need to change syntactically going forward?

or would nothing change and you guys(team polymer) just keep an eternal polyfill to support the current syntax?

**Comment by notwaldorf** [comment]
@retrocausal You should watch the Polymer summit talks on this topic! Fred's talk is a great starting point: https://www.youtube.com/watch?v=JH6jEcLxJEI
