### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by djbu** [notwaldorf/ama#60]
Hello Monica, a pleasure to talk with you, let me introduce myself: I'm an engineer and old styled backend dev, my last three years i was working with php, mostly with php the thing is i mostly work on ERP softwares and don't see so much motivation there. I do good stuff there but really is not so much interesting at the end of the day, large pl/sql and model codes. The last year i started to focus on angular and really it, but i think polymer 2 is the path. Could you please give some advices on how to get better at this?? I'm only a newbie in this world but i love all the great stuff that is being made there (SPA, PWA, Polymer for create your web components, just falling in love with that), Google is just great and i wanna work there. Btw hope that PWA will be the standard the next year :)

**Comment by notwaldorf** [comment]
Oof, that's a hard question. I tend to learn things best by doing -- either because at work I have to use a new tool or language (`gulp` i'm looking at you), or because on the side I want to work on a dumb project, and it requires something I don't know already (that's how I sort of learned `Polymer`, actually). If you want to get more comfortable with PWAs, just...make a PWA. :)

**Comment by djbu** [comment]
Thank you dame, i wanna try doning some own components when i end up my nativescript project. When codelabs will be releasing more tutos of polymer 2?
