### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AgMine** [notwaldorf/ama#62]
Hello, I'm new to Polymer and our company is using it for a major initiative.  Currently relatively few people use Polymer compared to jQuery...why do you think that is?  Do you expect Polymer to catch on, and when?

IF you are building a multi-tenant site where all the clients will want something styled exactly the same (except for their own logo to appear on a give page), considering ease and performance (as well as any shadow and shady dom issues), is it a problem just to create 1 css file that your Polymer pages will use/reference via class markers?  It seems overkill and over-engineering to worry about shared and custom styles.  Then have the URL interrogated by javascript to (on whatever page(s)) load the right client icon?  

We currently don't have any real known idea of the depth of customization clients may visually have, and not trying to boil the ocean...it doesn't seem to be a problem (not painting oneself into a corner with Polymer) to worry about this later, than try to create some master idea with mix ins and custom styles and stuff.  Because trumping priority when it comes to styling is local style tags on a page, followed by Polymer custom/shared-styles...followed by the more global .css file.  So as we find things that need customization/variance down the road, we can then just add that in later...with the .css being considered a "default" to the site?

I've seen many links and videos but your way/presentation seems to hit home with me.  Do you have any links/videos on styling scope as it relates to shady and shadow dom?  And how templates and dom-id technically tie-in to shadow and shady-dom?  Like, from a polymer perspective, an example of what the shadow dom is hiding from me?  And if Shady-dom is a shim, how (at a minutia level) it's doing what it's doing?  It seems odd...I understand everything form a conceptual level, but wanting to really understand it.

Thanks so much for your time...

**Comment by andrewperry** [comment]
Great questions! I hope Monica gets the chance to reply soon.

**Comment by notwaldorf** [comment]
Oh godddddd I completely missed this question and now it's a year later and I am the worst. Hello.

Here's some super late and prolly useless by now answers:
- we don't tend to compare polymer's popularity with jquery, because part of our goal is to make _web components_ popular, rather than Polymer itself, so a lot of our work goes in testing and developing the standard itself
- I'm not sure how to answer the "what shadow dom is hiding from me". It's basically encapsulating all the styles and the dom (see this [blog](https://meowni.ca/posts/shadow-dom/) i wrote recently), but you can always still pierce it with JavaScript, if you were really trying to, Polymer or not
- I also can't really explain at the minutia level how shady dom works -- you'd have to read the code for that. The basic idea is that it implements the missing features (like `slots`) and overrides a bunch of platform methods (like `querySelectorAll` for example), to try to return to you the results as if a shadow boundary is in place. How it does this specifically is all in the code (which I didn't write, and am not familiar with) 

Again, sorry for the absurd delay.

**Comment by andrewperry** [comment]
@notwaldorf Thanks for your comment! I think the question was really more about how to enable styling overrides as easily as possible in a multi-tenant environment using web components given clients like to be able to customise colour schemes and their logo etc.

**Comment by notwaldorf** [comment]
Oooh custom properties then! Custom properties are great for theming (see [this example](https://github.com/PolymerLabs/wizzywid/blob/master/app.js#L22) where i basically reskin the whole app based on a query parameter). 

For things like logo customization it's kind of up to you: maybe you want to pass the image as a distributed slot, maybe you want to pass the url and render/style it in the custom element, any of these would work.

**Comment by andrewperry** [comment]
wizzywid is so awesome @notwaldorf! Loved your presentation on it and so glad that it also provides a great example of the question @AgMine and I had. Hope to make it to a Polymer conference one day (maybe it needs to come to Australia)! Thanks
