### ISSUE TITLE
Will iron-form ever support multipart/form-data?

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#63]
Hi,

I imagine you been super busy with Polymer 2.0. Thanks for doing such great work on 2.0 and 1.0! 

The initial request for multipart/form-data support in iron-form was 2 years ago. The pre-submit workaround is ok in some circumstances, but since it overwrites pre-existing data in the form it's creates havoc in other circumstances. 

Can this be made a priority? It's been 2 years since it's initial request and it's common to have users post images with forms? 

Thanks,
-Darin

**Comment by notwaldorf** [comment]
Unfortunately, I haven't prioritized it for now -- in 2.0 `iron-form` has to change _completely_ (because type extensions are gone), and it's not ready as it is, so adding more features to it is unlikely 😢

If that's important for you, I recommend forking it and adding the features you need, or if you wait until 2.0, you can inherit from the new `IronForm` and add the features then.

Sorry I don't have a better answer. Making a form that works for everyone _and_ works in the same way as the native `<form>` everyone is used to is actually really hard 😵
