### ISSUE TITLE
tiny-care-terminal - personal preference to use var? 

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#64]
Old habits die hard and it's really tuff for me to get used to using `const` and `let` instead of `var`. If I had it my way, I would could keep using `var`.

I noticed in [tiny-care-terminal](https://github.com/notwaldorf/tiny-care-terminal) you used `var` instead. What made you choose to use `var`, just personal preference?

**Comment by notwaldorf** [comment]
Oh, I just don't write a lot of ES6 code yet (I write a lot of web side code where ES6 is still not everywhere), so I haven't got into the habit of using `const` and `let`. I think in theory they're nice -- it's reassuring to know I've set a `const` to something and can't accidentally change it because i'm a dummy. :)

**Comment by abdulhannanali** [comment]
@notwaldorf Don't you use Babel for the Web Side? If not, why?

**Comment by notwaldorf** [comment]
@abdulhannanali A lot of the work I do is on small, serverless projects, where I don't have a build step, and adding one would be very annoying. So generally, no.

**Comment by bryantee** [comment]
But Chrome supports most es6 syntax, and that's all that matters right? 😉
