### ISSUE TITLE
What podcasts do you listen to?

### ISSUE THREAD

**Issue by eush77** [notwaldorf/ama#7]

**Comment by notwaldorf** [comment]
I don't actually listen to any podcasts! I think I've only ever listened to "Serial". I'm not good at siting still and listening to people talking at me, so most of the time I start doing something, get distracted and realize I haven't paid attention to like half of the thing. Sorry!

**Comment by m3Lith** [comment]
Do you listen to music while working, though? Or something like [ambient sounds](http://asoftmurmur.com/)?

**Comment by notwaldorf** [comment]
@m3Lith Yup! I listen to a lot of music (here's my [last.fm](http://www.last.fm/user/notwaldorf), though it's been neglected recently because i've been travelling). I also work really well if there's a TV show in the background that I don't need to pay attention to, so when I'm working from home I might have episodes of Star Trek on loop.
