### ISSUE TITLE
Advice on going far

### ISSUE THREAD

**Issue by kauffmanes** [notwaldorf/ama#72]
Hey!

My name is Emily and I love all things code. My undergraduate degree was in computing & information studies, with a graphics focus. I realized I loved coding more than designing, so I've been working as a developer for a few years since then. Angular and Node are my favorite. It's a dream of mine to work at Google someday. Right now, I know I don't have the computer science background to get hired, but I am about to start an Information Science grad program at the University of Pittsburgh. Do you have any class/life recommendations that would help me prepare for a career at Google and in general, be an effective coder? First up this fall is data structures and intro to telecommunications. I'm also starting to be active on StackOverflow, writing stuff in my medium blog, and looking for open-source to contribute to, so I think that will help as well. Any advice would be greatly appreciated!

**Comment by notwaldorf** [comment]
Sorry for missing this! 

I get asked this a lot, so I've collected all the answers I've been giving in this [gist](https://gist.github.com/notwaldorf/4df04b5c9023aec6267bc7e66f284106). 

I think data structures and algorithms classes can at least prepare you for the google interviews (which are notoriously on the whiteboard, and about algorithms), but I don't think there's a real magic formula to becoming a good coder. Experience helps a lot -- one of the things that helped me the most is code reviews from way more experienced developers. Much like with cooking or baking, once you do the same thing a thousand times you develop a bit of intuition about it ("this bread is underdone because the dough doesn't spring back" vs "i don't know if this bread is underdone, i baked it for as long as the recipe said"), and developers who've been working for a bit tend to have accumulated these instincts (that I promise you too will develop!). If you're looking for code reviews, or a general question about "how you would build this thing" (but pls dont make me do your homework lol), ping me -- I can totally try to help!

If blogging works for you, that's great! I like writing down things I discover (whether publicly or in a note app) because when future Monica has a similar problem, I can just look it up. 

Good luck! Let me know how it goes!
