### ISSUE TITLE
What is your favorite book and why?

### ISSUE THREAD

**Issue by eush77** [notwaldorf/ama#8]

**Comment by notwaldorf** [comment]
Ugh, this is a hard question. I really, really like books and have a very hard time picking a favourite, because they hit me differently in the feels. The shortest list that I can come up with is:

- The Little Prince, by Antoine de Saint-Exupéry, because it has an answer to anything
- Neverwhere by Neil Gaiman, because I love the idea that boring, everyday things have a secret life
- Brief Interviews with Hideous Men by D.F.Wallace, and really, everything he's ever written, because it's lovely

And let's be honest, I'll re-read Harry Potter any day.

**Comment by eush77** [comment]
Thank you!

**Comment by kenhkelly** [comment]
+1 For HP
