### ISSUE TITLE
Polymerless webcomponents projects

### ISSUE THREAD

**Issue by anxolerd** [notwaldorf/ama#82]
Hi,

Liked your webcomponents videos a lot — they are quite inspiring.
What I'd like to ask is whether you know any more-less big project (at least of size of [Mojibrag](https://github.com/notwaldowf/mojibrag) (BTW, is it still alive?)), which uses webcomponents, but uses pure webcomponents without all those [Polymers](https://www.polymer-project.org/) or [X-tags](https://x-tag.github.io/).

I don't see anything bad in using those libraries, but would like to see some project with pure webcomponents in the wild.

The interest is completely educational.

P.S. [A-Frame](https://aframe.io/) while uses webcomponents, does a lot of things in their own way, thus not an option =(.

**Comment by notwaldorf** [comment]
The reason why you're probably not seeing any library-free large projects that use web components is that there's a lot of boilerplate needed to write a web component, since the spec is so low level. This is why libraries like Polymer or lit-html that already do this for you tend to be preferred; otherwise you end up writing your own generic template stamping method, `ready()` callback, etc, so that you don't copy paste the same code in every one of your vanilla web components, and at this point you're basically writing your own tiny Polymer -- might as well use the tested one :)

(and to answer your specific question: i do not know of any pure vanilla web components apps that are bigger than a demo)

**Comment by anxolerd** [comment]
Found this project in progress.

https://github.com/criticalbh/vanilla-web-components-spa

According to the description it is going to be Medium clone built as SPA with vanilla webcomponents.
