### ISSUE TITLE
Is Chrome a new IE? If so, how to fix it?

### ISSUE THREAD

**Issue by anxolerd** [notwaldorf/ama#84]
According to [pretty old article on "the verge"](https://www.theverge.com/2018/1/4/16805216/google-chrome-only-sites-internet-explorer-6-web-standards), there are more and more sites, which are designed specifically to work best with chrome, often ignoring other browsers. This is quite similar to what happened earlier with Internet Explorer. What is your opinion on that?
If you consider this as a problem, how do you think this problem can be solved. If not -- why?

Thanks in advance.

**Comment by notwaldorf** [comment]
Ehhhh I don't really comment on any articles people write about Chrome, since i'm not a Chrome spokesperson, there's a lot of articles, and tbh people can just write whatever they want. I think that article in particular is pretty sloppy journalism -- imo the difference is a bit subtle: IE tended to ship proprietary APIs and (in later years) fall behind on specs, and Chrome just implements specs before other browsers. Not implementing features drags the platform down, while implementing features quickly pushes it forward (but can cause a bit of a strain on the ecosystem).

That being said, shipping sites and apps on one browser alone is bad, both for the app and the users, and does nothing good for the ecosystem. Chrome engineers don't want you to ship apps on Chrome only, and your users don't, so just .... don't do that.

**Comment by anxolerd** [comment]
Thanks for honest answer, and sorry for inconvenient question.
