### ISSUE TITLE
How do you keep up with the differences between the major browsers? 

### ISSUE THREAD

**Issue by dalanmiller** [notwaldorf/ama#88]
Besides https://caniuse.com do you have any recommendations? Do you have a test suite you run to compare how things are rendered and look for inconsistencies? Would be super keen to hear your perspective!

**Comment by notwaldorf** [comment]
Hmm I don't really have a better approach. Usually, when I write an app I know which "newish" features I'm using (DOM apis or JS language features), and then a matrix sort of emerges re: compatibility. For example, for `pwa-starter-kit`, we literally wrote a [table](https://github.com/Polymer/pwa-starter-kit/wiki/2.1.-Browser-support) with all the features we're using and what browsers support them, so that we can figure out what the compiled bundles would look like.
