### ISSUE TITLE
What alfred workflows do you use?

### ISSUE THREAD

**Issue by evaryont** [notwaldorf/ama#9]
I read your recent interview on [The Setup](https://usesthis.com/interviews/monica.dinculescu/) and you mention you use Alfred. I'm curious, what workflows do you end up using a lot?

**Comment by notwaldorf** [comment]
I don't really use workflows anymore (my license expired, I switched computers and lost all my workflows*), but I still find the Alfred search waaaaay better than Spotlight, which is why I can't stop using it. I haven't tried the new Spotlight on El Capitan, and I've heard good things about it, but I doubt I'll ever go back.

* my favourites were: the script that cleaned up screenshots from my desktop, and the one that converted hex-rgb  and saved me a google search. Those were the days.
