### ISSUE TITLE
Good Web Components codebases to read?

### ISSUE THREAD

**Issue by alex-nt** [notwaldorf/ama#92]
What are some good web components codebases to read? I want to start learning more about the spec and not a specific framework. Thanks :smile:

**Comment by notwaldorf** [comment]
Oh hmm, that's a good question I don't have an answer to. Most Big Apps that would be worth looking at would probably use some form of small library/helpers along web components, since out of the box 🚾 are really boilerplate-y (you'd have to figure out how to do your own template stamping, updating, data bindings, etc).

For `pwa-starter-kit`, the project i've recently been working on, we've started using `lit-html` (and a `lit-element` base class built with `lit-html`) for this. Here's some [sample apps](https://github.com/Polymer/pwa-starter-kit/wiki#sample-apps--) we've built with it, that you might find useful from a code perspective. They're pretty big apps (not huge, just featureful), and they show different ways to organize your web components and smush them together.

Hope this helped!
