### ISSUE TITLE
Web Components & Async rendering

### ISSUE THREAD

**Issue by gregorym** [notwaldorf/ama#93]
IMO one of the biggest selling point of React right now is async rendering. Stenciljs does also offer async rendering however you are forced to use Typescript, which I don't like.

Do you have thoughts on the topic and do you know if Polymer or other Web Component libraries are working on async rendering?

**Comment by notwaldorf** [comment]
I don't really know a ton on this topic. Web components use the actual dom, not a vdom, and the actual dom is fundamentally imperative, which is why async rendering doesn't really translate off the bat there. I asked @developit, and he said 
"AsyncAppend and Template Instantiation both move towards those goals though", so there's that!
